function [xk] = gmres(A, b, x0, k, C)
%% Approximate the solution to the linear system Ax = b using GMRES
% Approximate the solution to the linear system Ax = b using C iterations
% of the Generalised Minimum Residual Method (GMRES) that generates k
% basis vectors using Arnoldi's method.
%
%   Input:
%       A: a real nxn matrix.
%       b: a real nx1 vector.
%       x0: an approximation of the solution.
%       k: the number of vectors generated by the Arnoldi method each
%           iteration of the GMRES method.
%       C: the number of iterations of the GMRES method.
%
%   Output:
%       x: the solution vector.
%

% initialise the current approximation of the solution
xk = x0;

% perform GMRES using the current approximation of the solution
for z = 1:C
    
    % initialise for the "first" Krylov subspace vector
    r0 = b - A * xk;
    beta = norm(r0);
    
    % generate the orthonormal basis
    [Q, H] = arnoldi_vectors(A, r0, k);

    % compute the minimiser (least squares problem)
    k = min(size(Q));
    y = (H' * H) \ (H' * beta * eye(k+1, 1));

    % update the solution
    xk = xk + Q * y;
end
end
